# config/services.yaml
parameters:
# Можно добавить кастомные параметры здесь, например:
# app.email_sender: 'no-reply@example.com'

security:
    firewalls:
        main:
            form_login:
                username_parameter: 'email'
                password_parameter: 'password'

    password_hashers:
        App\Entity\User:
            algorithm: auto

services:
    # Дефолтные настройки для всех сервисов
    _defaults:
        autowire: true      # Автоматическое внедрение зависимостей
        autoconfigure: true # Автоматическая регистрация тегов
        public: false       # Сервисы по умолчанию приватные

    # Автозагрузка всех классов в src/ как сервисов
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'  # Исключаем тесты

    # Явно объявляем контроллеры как публичные сервисы
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
        public: true

    Symfony\Component\Security\Http\Authentication\AuthenticationUtils:
        public: true